<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Faspay-SysDev-Aan" failures="1" tests="3" name="Command line test" time="41.234" errors="0" timestamp="2023-02-04T23:29:51 WIB">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="18.084"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="15.463"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.142">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="Index 2 out of bounds for length 2">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at com.tia.cucumber.step_definitions.Hooks.setUp(Hooks.java:33)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Command line test -->
