<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Faspay-SysDev-Aan" failures="0" tests="2" name="com.tia.cucumber.step_definitions.RunnerTest" time="15.605" errors="1" timestamp="2023-02-04T23:29:52 WIB" skipped="0">
  <testcase classname="com.tia.cucumber.step_definitions.RunnerTest" name="runScenario" time="0.142">
    <error message="Index 2 out of bounds for length 2" type="java.lang.ArrayIndexOutOfBoundsException">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at com.tia.cucumber.step_definitions.Hooks.setUp(Hooks.java:33)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.tia.cucumber.step_definitions.RunnerTest" name="runScenario" time="15.463"/>
  <system-out/>
</testsuite> <!-- com.tia.cucumber.step_definitions.RunnerTest -->
